### ISSUE TITLE
Arm and Disarm trough serial

### ISSUE THREAD

**Issue by tvigouroux** [gytisgreitai/paradox-security-arduino#1]
It is possible or you have experience arming and disarming the alarm trough this interface?

**Comment by gytisgreitai** [comment]
IMHO this is possible, since this can be done with third party modules that hook into the same serial port. Not sure how though.

**Comment by javierferwolf** [comment]
Good day!
How can I apply the security switch that restarts HardwareSerial after 3 consecutive failed packet decoding attempts?
I have the problem that after a few minutes of operation! can not read the serial again!
thank you
